/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class android_serialport_api_SerialPort */

#ifndef _Included_android_serialport_api_SerialPort
#define _Included_android_serialport_api_SerialPort
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     android_serialport_api_SerialPort
 * Method:    open
 * Signature: (Ljava/lang/String;II)I
 */
JNIEXPORT jint JNICALL Java_android_1serialport_1api_SerialPort_open
  (JNIEnv *, jclass, jstring, jint, jint);

/*
 * Class:     android_serialport_api_SerialPort
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_android_1serialport_1api_SerialPort_close
  (JNIEnv *, jobject);

/*
 * Class:     android_serialport_api_SerialPort
 * Method:    setBaseData
 * Signature: (Landroid_serialport_api/SerialPort/BaseData;)I
 */
JNIEXPORT jint JNICALL Java_android_1serialport_1api_SerialPort_setBaseData
  (JNIEnv *, jobject, jobject);

/*
 * Class:     android_serialport_api_SerialPort
 * Method:    setPayType
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_android_1serialport_1api_SerialPort_setPayType
  (JNIEnv *, jobject, jint);

/*
 * Class:     android_serialport_api_SerialPort
 * Method:    setWaterVolume
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_android_1serialport_1api_SerialPort_setWaterVolume
  (JNIEnv *, jobject, jint);

/*
 * Class:     android_serialport_api_SerialPort
 * Method:    setDueTime
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_android_1serialport_1api_SerialPort_setDueTime
  (JNIEnv *, jobject, jint);

/*
 * Class:     android_serialport_api_SerialPort
 * Method:    setWaterSwitch
 * Signature: (ZI)I
 */
JNIEXPORT jint JNICALL Java_android_1serialport_1api_SerialPort_setWaterSwitch
  (JNIEnv *, jobject, jboolean, jint);

/*
 * Class:     android_serialport_api_SerialPort
 * Method:    setFilterLife
 * Signature: ([II)I
 */
JNIEXPORT jint JNICALL Java_android_1serialport_1api_SerialPort_setFilterLife
  (JNIEnv *, jobject, jintArray, jint);

/*
 * Class:     android_serialport_api_SerialPort
 * Method:    setVerSwitch
 * Signature: (Z)I
 */
JNIEXPORT jint JNICALL Java_android_1serialport_1api_SerialPort_setVerSwitch
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     android_serialport_api_SerialPort
 * Method:    setCurrentTime
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_android_1serialport_1api_SerialPort_setCurrentTime
  (JNIEnv *, jobject, jstring);

/*
 * Class:     android_serialport_api_SerialPort
 * Method:    getFileDescriptor
 * Signature: ()Ljava/io/FileDescriptor;
 */
JNIEXPORT jobject JNICALL Java_android_1serialport_1api_SerialPort_getFileDescriptor
  (JNIEnv *, jobject);

/*
 * Class:     android_serialport_api_SerialPort
 * Method:    getBaseData
 * Signature: (Landroid_serialport_api/SerialPort/BaseData;)I
 */
JNIEXPORT jint JNICALL Java_android_1serialport_1api_SerialPort_getBaseData
  (JNIEnv *, jobject, jobject);

/*
 * Class:     android_serialport_api_SerialPort
 * Method:    initBaseData
 * Signature: (Landroid_serialport_api/SerialPort/BaseData;)I
 */
JNIEXPORT jint JNICALL Java_android_1serialport_1api_SerialPort_initBaseData
  (JNIEnv *, jobject, jobject);

/*
 * Class:     android_serialport_api_SerialPort
 * Method:    initWaterState
 * Signature: (Landroid_serialport_api/SerialPort/WaterStateInfo;)I
 */
JNIEXPORT jint JNICALL Java_android_1serialport_1api_SerialPort_initWaterState
  (JNIEnv *, jobject, jobject);

/*
 * Class:     android_serialport_api_SerialPort
 * Method:    getWaterState
 * Signature: (Landroid_serialport_api/SerialPort/WaterStateInfo;)I
 */
JNIEXPORT jint JNICALL Java_android_1serialport_1api_SerialPort_getWaterState
  (JNIEnv *, jobject, jobject);

/*
 * Class:     android_serialport_api_SerialPort
 * Method:    setWaterState
 * Signature: (Landroid_serialport_api/SerialPort/WaterStateInfo;)I
 */
JNIEXPORT jint JNICALL Java_android_1serialport_1api_SerialPort_setWaterState
  (JNIEnv *, jobject, jobject);

/*
 * Class:     android_serialport_api_SerialPort
 * Method:    getReturn
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_android_1serialport_1api_SerialPort_getReturn
  (JNIEnv *, jobject);

/*
 * Class:     android_serialport_api_SerialPort
 * Method:    setUnbind
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_android_1serialport_1api_SerialPort_setUnbind
  (JNIEnv *, jobject);

/*
 * Class:     android_serialport_api_SerialPort
 * Method:    setTemperatureCorrectionPlus
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_android_1serialport_1api_SerialPort_setTemperatureCorrectionPlus
  (JNIEnv *, jobject, jint);

/*
 * Class:     android_serialport_api_SerialPort
 * Method:    setTemperatureCorrectionReduce
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_android_1serialport_1api_SerialPort_setTemperatureCorrectionReduce
  (JNIEnv *, jobject, jint);

/*
 * Class:     android_serialport_api_SerialPort
 * Method:    setFlowCorrectionPlus
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_android_1serialport_1api_SerialPort_setFlowCorrectionPlus
  (JNIEnv *, jobject, jint);

/*
 * Class:     android_serialport_api_SerialPort
 * Method:    setFlowCorrectionReduce
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_android_1serialport_1api_SerialPort_setFlowCorrectionReduce
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
